# Generated by Django 2.1.5 on 2022-03-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0, unique=True)),
                ('coordinator', models.CharField(max_length=128)),
                ('course_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_id', models.IntegerField(default=0, unique=True)),
                ('lec_name', models.CharField(max_length=128)),
                ('length', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=128)),
                ('time', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecQuiz.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField(default=0, unique=True)),
                ('quiz_name', models.CharField(max_length=128)),
                ('question', models.CharField(max_length=128)),
                ('answer', models.CharField(max_length=128)),
                ('correct_answer', models.CharField(max_length=128)),
                ('lecture_time', models.IntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecQuiz.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('psw', models.CharField(max_length=128)),
                ('email_id', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to='RecQuiz.User'),
        ),
    ]
