# Generated by Django 2.1.5 on 2022-03-19 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('coordinator', models.CharField(max_length=128)),
                ('course_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='www.baidu.com', max_length=128)),
                ('lec_id', models.IntegerField(default=0)),
                ('lec_name', models.CharField(max_length=128)),
                ('length', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecQuiz.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=128)),
                ('answer1', models.CharField(max_length=128)),
                ('answer2', models.CharField(max_length=128)),
                ('answer3', models.CharField(max_length=128)),
                ('answer4', models.CharField(max_length=128)),
                ('correct_answer', models.CharField(max_length=128)),
                ('lecture_time', models.IntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecQuiz.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
