# Generated by Django 2.1.5 on 2022-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.CharField(default='www.baidu.com', max_length=128),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.CharField(default='true', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer3',
            field=models.CharField(default='false', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer4',
            field=models.CharField(default='none of this', max_length=128),
            preserve_default=False,
        ),
    ]
